# Generated by Django 3.0.7 on 2020-06-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200609_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(choices=[('tata', 'TATA'), ('mahindra', 'Mahindra'), ('daewoo', 'Daewoo')], max_length=20),
        ),
    ]
