# Generated by Django 3.0.7 on 2020-06-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200609_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
